services:
  db:
    image: postgres:17.5
    container_name: drupal-db
    environment:
      POSTGRES_PASSWORD: postgres@12345
    volumes:
      - drupal-data:/var/lib/postgressql/data
  web:
    build: .
    image: custome-drupal
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/vae/www/html/sites
volumes:
  drupal-data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
